name: Release and Publish

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., patch, minor, major)'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build library
        run: npm run build

      - name: Get version from tag or bump version
        id: version
        run: |
          if [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == refs/tags/* ]]; then
            # Extract version from tag (remove 'v' prefix)
            VERSION=${GITHUB_REF#refs/tags/v}
            echo "NEW_VERSION=$VERSION" >> $GITHUB_ENV
            echo "TAG_NAME=v$VERSION" >> $GITHUB_ENV
          elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            # Bump version and create tag
            npm version ${{ github.event.inputs.version }} --no-git-tag-version
            NEW_VERSION=$(node -p "require('./package.json').version")
            echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
            echo "TAG_NAME=v$NEW_VERSION" >> $GITHUB_ENV
            
            # Create and push tag
            git add package.json package-lock.json
            git commit -m "chore: bump version to v$NEW_VERSION"
            git tag "v$NEW_VERSION"
            git push origin main
            git push origin "v$NEW_VERSION"
          fi

      - name: Create GitHub Release
        run: |
          gh release create "${{ env.TAG_NAME }}" \
            --title "Release ${{ env.TAG_NAME }}" \
            --notes "## Changes in ${{ env.TAG_NAME }}
          
          A better keypress library for native JavaScript with TypeScript support.
          
          ## Installation
          \`\`\`bash
          npm install better-keypress@${{ env.NEW_VERSION }}
          \`\`\`
          
          ## Demo
          [View Demo](https://better-keypress.netlify.app/)" \
            ./dist/index.js#better-keypress.js \
            ./dist/index.esm.js#better-keypress.esm.js \
            ./dist/index.d.ts#better-keypress.d.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} 