name: Release and Publish

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., patch, minor, major)'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.RELEASE_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build library
        run: npm run build
    #   - name: Create GitHub Release
    #     id: create_release
    #     uses: actions/create-release@v1
    #     env:
    #       GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
    #     with:
    #       tag_name: v${{ env.NEW_VERSION }}
    #       release_name: Release v${{ env.NEW_VERSION }}
    #       body: |
    #         ## Changes in v${{ env.NEW_VERSION }}
            
    #         A better keypress library for native JavaScript with TypeScript support.
            
    #         ## Installation
    #         ```bash
    #         npm install better-keypress@${{ env.NEW_VERSION }}
    #         ```
            
    #         ## Demo
    #         [View Demo](https://better-keypress.netlify.app/)
    #       draft: false
    #       prerelease: false

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Upload CJS build
        uses: actions/upload-release-asset@v1
        env:
          RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/index.js
          asset_name: better-keypress.js
          asset_content_type: application/javascript

      - name: Upload ESM build
        uses: actions/upload-release-asset@v1
        env:
          RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/index.esm.js
          asset_name: better-keypress.esm.js
          asset_content_type: application/javascript

      - name: Upload TypeScript definitions
        uses: actions/upload-release-asset@v1
        env:
          RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/index.d.ts
          asset_name: better-keypress.d.ts
          asset_content_type: text/plain 